var intro ="I am the intro. I am the start. you ran for you life now you have to choose between, running through the forst or running through the highway. Choose your path!"

var cforest ="Go through the forest"
var chighway ="Go to the highway"

var forest = "You decided to go through the forest and try and avoid heavy populated areas. You head through the forest and make your way to the where you remember passing by some houses. As you travel through the forest you hear a loud explosion,and you see a huge smoke cloud through the clearing. It is in the same direction as the houses and you can start to see the houses as you almost exit the forest. You see 4 houses and 1 is on fire, probably the explosion you heard. Which house do you go to house 1 is closest to the fire, house 2 is the second closest to the fire and the third is the furest away from the house on fire but closest to the main road"

var chouse1 ="" 
var chouse2 ="" 
var chouse3 =""
var crv =""
var cenp =""
var cwwt =""
var cwal1 =""
var cwal2 =""
var cwal3 =""

var highway =""
var house1 =""
var house2 =""
var house3 =""
var rv =""
var enp =""
var wwt =""
var wal1 =""
var wal2 =""
var wal3 =""